### PR TITLE
[VIDEO-2193] Update for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jawilson**
## Test Procedure
Verify the workflow succeeds.

-OR-

1. Use Ubuntu 22.04 LTS
2. Build/install the AWS C++ SDK version `1.10.30` and dependencies (it's probably easiest to just follow the [Vera guide](https://github.com/blinemedical/vera/blob/afe35481d069a8abc25efe261764b2d2a46ee03a/avp/README.Ubuntu.md))
3. Build, install, and test this repo

### CODE REVIEW

**Comment by btgoodwin** [comment]
Is the plan to update the CI build as well to 22.04 / at least make it work?

**Comment by jawilson** [comment]
@btgoodwin oops. I updated the runner version, however the `setup-gstreamer` action doesn't support `22.04` so I created https://github.com/blinemedical/setup-gstreamer/pull/122 to update the GH Action, once that's merged we can re-trigger the build and it'll succeed.

**Review by btgoodwin — APPROVED** [review]
Looks like we may need tickets to update the dockerfile/build instructions for the AVP and other projects that utilize this plugin.

**Comment by jawilson** [comment]
@btgoodwin yup, it's just the AVP right now AFAIK, but we have VIDEO-2192 (https://github.com/blinemedical/vera/pull/365) for that.

**Pull request merged**
