### PR TITLE
[VIDEO-3064] Update to 1.24.8-lldc

### PR DESCRIPTION
**Pull request by btgoodwin**
VIDEO-3064

*Description of changes:*

Updated github actions to point at 1.24.8-lldc / 1.24.8 respectively.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by saraboule** [comment]
^^ well that's a new label I have not seen before!

**Comment by btgoodwin** [comment]
> ^^ well that's a new label I have not seen before!

We don't have our usual labels so I thought this one-liner would be funny, and then the linux build broke when pointed to the 1.24.8 tag. :-|  Something about winasm not being available.

Frankly I'm not sure why we have a linux workflow for this unless it's a carry-over from the upstream.

**Comment by saraboule** [comment]
> > ^^ well that's a new label I have not seen before!
> 
> We don't have our usual labels so I thought this one-liner would be funny, and then the linux build broke when pointed to the 1.24.8 tag. :-| Something about winasm not being available.
> 
> Frankly I'm not sure why we have a linux workflow for this unless it's a carry-over from the upstream.


don't we use the s3sink in the AVP?

**Review by saraboule — APPROVED** [review]

**Comment by btgoodwin** [comment]
> > > ^^ well that's a new label I have not seen before!
> > 
> > 
> > We don't have our usual labels so I thought this one-liner would be funny, and then the linux build broke when pointed to the 1.24.8 tag. :-| Something about winasm not being available.
> > Frankly I'm not sure why we have a linux workflow for this unless it's a carry-over from the upstream.
> 
> don't we use the s3sink in the AVP?

Yes, but it's compiled from source as part of the container provisioning, so there's no direct relationship from the workflow to downstream projects like there is for the windows package.

**Pull request merged**
